# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'weibo', b'\xe5\xbe\xae\xe5\x8d\x9a'), (b'google', b'\xe8\xb0\xb7\xe6\xad\x8c'), (b'github', b'GitHub'), (b'facebook', b'FaceBook'), (b'qq', b'QQ')], default=b'a', max_length=10, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('appkey', models.CharField(max_length=200, verbose_name=b'AppKey')),
                ('appsecret', models.CharField(max_length=200, verbose_name=b'AppSecret')),
                ('callback_url', models.CharField(default=b'http://www.baidu.com', max_length=200, verbose_name=b'\xe5\x9b\x9e\xe8\xb0\x83\xe5\x9c\xb0\xe5\x9d\x80')),
                ('is_enable', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': 'oauth\u914d\u7f6e',
                'verbose_name_plural': 'oauth\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='OAuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('nikename', models.CharField(max_length=50, verbose_name=b'\xe6\x98\xb5\xe7\xa7\xb0')),
                ('token', models.CharField(blank=True, max_length=150, null=True)),
                ('picture', models.CharField(blank=True, max_length=350, null=True)),
                ('type', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('matedata', models.CharField(blank=True, max_length=3000, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': 'oauth\u7528\u6237',
                'verbose_name_plural': 'oauth\u7528\u6237',
            },
        ),
    ]
