# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnTrackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
                ('lat', models.FloatField(verbose_name=b'\xe7\xba\xac\xe5\xba\xa6')),
                ('lon', models.FloatField(verbose_name=b'\xe7\xbb\x8f\xe5\xba\xa6')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'ordering': ['created_time'],
                'get_latest_by': 'created_time',
                'verbose_name': 'OwnTrackLogs',
                'verbose_name_plural': 'OwnTrackLogs',
            },
        ),
    ]
